# Run docker image, mounting/running service source ("rundev" vs "runpkg")

# In Order to Run Docker in interactive mode
# 1. uncomment/comment to replace hwa_server.py with /bin/bash
# 2. execute command:  bash$ docker-compose run --rm magen_hwa

version: "2"

networks:
  default:
    external:
      name: magen_net

services:
  magen_hwa:
    build: .
    image: magen_hwa:v1.0
    container_name: magen_hwa
    command: bash -c '(echo "LAUNCHING MAGEN_HWA CONTAINER.  NOTE -- OUTPUT ALSO LOGGED UNDER DIR=hwa/.. (WORKSPACE ROOT) TO hwa_server.log FILE AND TO hwa_logs/ SUBDIRECTORY" && python3 ./hwa_server/hwa_server.py --console-log-level 'info' --log-dir ../hwa_logs) 2>&1 | tee -a ../hwa_server.log'
    #command: /bin/bash
    ports:
      - "443:5002"
      - "5002:5002"
    volumes:
      - ../..:/opt/server
    stdin_open: true 
    tty: true
    networks:
      - default
